name: check compiling and rootkit installing
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  check:
    env:
      rootkit: server.ko
    strategy:
      fail-fast: false
      matrix:
        os:[ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
    runs-on:
        runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: checking client compiling
      run: make --directory=client

    - name: checking rootkit compiling
      run: |
        cd server && make 
        ls -la
    - name: checking module installing
      run: | 
        sudo insmod $rootkit
        sudo dmesg | grep "Loading module..."
